
services:
  
  postgres:
    image: postgres:15-alpine
    container_name: bank_postgres
    environment:
      
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network

  
  maven:
    image: maven:3.8.6-eclipse-temurin-17
    volumes:
      
      - ./:/usr/src/app
      - maven-repo:/root/.m2
    working_dir: /usr/src/app
    command: mvn clean package -DskipTests
    depends_on:
      - postgres
    networks:
      - bank_network

  
  tomcat:
    image: tomcat:10.0-jdk17
    ports:
      
      - "8091:8080"
    volumes:
      - ./target/bank-rest.war:/usr/local/tomcat/webapps/bank-rest.war
    depends_on:
      - postgres
      - maven
    environment:
      
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bankdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - bank_network


volumes:
  postgres_data:
  maven-repo:


networks:
  bank_network:
    driver: bridge